version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm test

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - deploy:
          name: Deploy Master to NPM
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build
              npm publish
            fi
